GITTIME="$(date -d "$(git log -1 --format=format:%ci)" "+%Y/%m/%d %H:%M:%S")"
GITHASH="$(git rev-parse -q --short --verify HEAD)"
GITDESCRIBE="$(git describe)"
GITREPOURL="$(git remote get-url origin|sed -e 's/git@github.com:/http:\/\/github.com\//'|sed -e 's/\.git$//')"

echo "#ifndef _GITVERSION_H_"
echo "#define _GITVERSION_H_"
echo "#define GITTIME \"$GITTIME\""
echo "#define GITHASH \"$GITHASH\""
echo "#define GITDESCRIBE \"$GITDESCRIBE\""
git diff-index --quiet HEAD -- || echo "#define GITMODIFIED 1"
echo "#define GITREPOURL \"$GITREPOURL\""
echo "#endif"
